"""Rename metadata column to meta_info

Revision ID: 73029b4ebc0d
Revises: 63fe804521b9
Create Date: 2024-05-20 10:33:31.214508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73029b4ebc0d'
down_revision = '63fe804521b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_feed') as batch_op:
        batch_op.alter_column('metadata', new_column_name='meta_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_feed') as batch_op:
        batch_op.alter_column('meta_info', new_column_name='metadata')
    # ### end Alembic commands ###
